name: GESAD
description: Grupo de Engenharia de Software e Sistemas Distribu√≠dos
url: https://gesad.github.io/

markdown: kramdown
permalink: /:categories/:title/
future: true

exclude:
  - "*.class"
  - "*.cpp"
  - "*.h"
  - "*.hh"
  - "*.ipynb"
  - "*.jar"
  - "*.java"
  - "*.nb"
  - "*.py"
  - "*.R"
  - "*.rb"
  - "*.Rmd"
  - "*.branches"
  - "*.csv"
  - "*.fasta"
  - "*.kml"
  - "*.log"
  - "*.mcc"
  - "*.newick"
  - "*.nex"
  - "*.tsv"
  - "*.tips"
  - "*.trees"
  - "*.txt"
  - "*.zip"
  - "*.gz"
  - "Gemfile"
  - "Gemfile.lock"

# GitHub projects
projects:
  - lotus-tool/lotus-tool
